### ISSUE TITLE
Make the scrolling bar directly interactable - feature request (?)

### ISSUE THREAD

**Issue by Spincervino** [Paari/chrome-reader-extension#2]
Loving the app marvelous simplicity
I just wish i could move up and down directly the bar for scrolling.

Maybe i'm having a bug with the scrolling bar in the page behind the _Reeader view_.
The scrolling bar of the normal tab under the view is interactable, but not the one of the app.

Thanks for your time in advance, 
Spincer

**Comment by Paari** [comment]
@Spincervino Thank you!

Yes, there is some issue with the scroll. The reader has a scrollbar and there is the main scroll bar of the page. I will modify the script a little to disable the background scroll so that you can take better control of the scrolling. I will try to fix as soon as I get some time to work on it.

Thank you for taking the time to point this out, let me know if there is any feature you would like me to add.

**Comment by keeferrourke** [comment]
Is there an update on this? I'm being forced to use Chrome a lot lately and really miss reader mode from Firefox. I just found this extension and I would like to love it, but this scrollbar issue is a downer :(

@Paari I'm also happy to contribute code if you can point me in the right direction.

**Comment by Paari** [comment]
@keeferrourke I haven't gotten time to look into this issue. If you have some familiarity with React you can play around with the code, the logic is in the file _**/src/App.js**_.

I believe it will need some kind of simple js code that can disable the scroll in the body tag.
If you can look into it, that would be really helpful!

If I am able to get some time to work on it and fix the issue, I will update it here.

**Comment by Paari** [comment]
@Spincervino @keeferrourke  This is fixed now and the extension is also updated with the fix.

**Comment by Spincervino** [comment]
Thank you Paari! :D
